/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * Mirrors `main/framework/api/problems.py:ProblemDetail` so the frontend can
 * type-check error envelopes returned by the FastAPI exception handlers and
 * `problem_response` helper.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */

/** Default `type` URI used when a problem omits a specific type identifier. */
export const PROBLEM_TYPE_DEFAULT = "about:blank" as const;

/** Standard `Content-Type` for RFC 7807 responses. */
export const PROBLEM_MEDIA_TYPE = "application/problem+json" as const;

/**
 * RFC 7807 problem details object.
 *
 * Matches the Pydantic `ProblemDetail` model on the backend.
 */
export interface ProblemDetail {
  /** URI reference identifying the problem type. Defaults to `about:blank`. */
  type: string;
  /** Short, human-readable summary of the problem type. */
  title: string;
  /** HTTP status code generated by the origin server. */
  status: number;
  /** Human-readable explanation specific to this occurrence. */
  detail?: string;
  /** URI reference identifying this specific occurrence. */
  instance?: string;
}

/**
 * Runtime error wrapping an `application/problem+json` response from the API.
 *
 * Throw this (or its subclasses) from fetch/Axios interceptors so call sites
 * can react to typed problem details instead of raw HTTP statuses.
 */
export class ApiError extends Error {
  /** HTTP status code from the response. */
  public readonly status: number;
  /** Parsed RFC 7807 problem details body. */
  public readonly problem: ProblemDetail;
  /** Optional upstream request identifier (from `X-Request-ID` or similar). */
  public readonly requestId?: string;

  constructor(problem: ProblemDetail, requestId?: string) {
    super(problem.detail ?? problem.title);
    this.name = "ApiError";
    this.status = problem.status;
    this.problem = problem;
    this.requestId = requestId;
    // Restore prototype chain when targeting ES5 / transpiled output.
    Object.setPrototypeOf(this, ApiError.prototype);
  }
}

/**
 * Type guard that narrows an unknown thrown value to {@link ApiError}.
 *
 * @param e - Value caught from a `try`/`catch` or rejection handler.
 * @returns `true` when `e` is an {@link ApiError} instance.
 */
export function isApiError(e: unknown): e is ApiError {
  return e instanceof ApiError;
}
