"""RFC 7807 Problem Details for HTTP APIs (application/problem+json).

Provides :class:`ProblemDetail` (Pydantic model) and :func:`problem_response`
helper used by FastAPI exception handlers and routes to return standardized
error envelopes per https://datatracker.ietf.org/doc/html/rfc7807.
"""

from __future__ import annotations

from fastapi.responses import JSONResponse
from pydantic import BaseModel, ConfigDict

__all__ = ["ProblemDetail", "problem_response"]


class ProblemDetail(BaseModel):
    """RFC 7807 problem details object.

    Members:
        type: URI reference identifying the problem type (default ``about:blank``).
        title: Short, human-readable summary of the problem type.
        status: HTTP status code generated by the origin server.
        detail: Human-readable explanation specific to this occurrence.
        instance: URI reference identifying this specific occurrence.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": "about:blank",
                "title": "Not Found",
                "status": 404,
                "detail": "Resource abc not found",
                "instance": "/api/v1/workflows/abc",
            }
        }
    )

    type: str = "about:blank"
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None


def problem_response(
    status: int,
    title: str,
    detail: str | None = None,
    type_uri: str = "about:blank",
    instance: str | None = None,
) -> JSONResponse:
    """Build an ``application/problem+json`` :class:`JSONResponse`.

    Args:
        status: HTTP status code to return.
        title: Short, human-readable summary.
        detail: Optional human-readable explanation of this occurrence.
        type_uri: URI reference identifying the problem type.
        instance: Optional URI reference identifying this specific occurrence.

    Returns:
        A :class:`JSONResponse` with the correct status and ``problem+json`` media type.
    """
    problem = ProblemDetail(
        type=type_uri,
        title=title,
        status=status,
        detail=detail,
        instance=instance,
    )
    return JSONResponse(
        status_code=status,
        content=problem.model_dump(exclude_none=True),
        media_type="application/problem+json",
    )
