/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * Mirrors `main/framework/api/problems.py:ProblemDetail` so the frontend can
 * type-check error envelopes returned by the FastAPI exception handlers and
 * `problem_response` helper.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 *
 * @deprecated 自后端重构后不再使用 RFC 7807 格式。
 * 后端现在返回 {code, message, data, trace_id}，请使用 {@link ApiErrorBody}。
 * 此处保留以避免破坏遗留引用，阶段四统一清理。
 */

/**
 * 后端 ApiResponse 错误格式 — 对应 src/main/infra/api_envelope.py
 *
 * 后端统一错误信封字段，HTTP 层(axios/fetch 拦截器)解析后包装进 {@link ApiError}。
 */
export interface ApiErrorBody {
  /** 后端 ErrorCode 数值 (0=成功, 1xxx=业务, 2xxx=系统, 3xxx=基础设施) */
  code: number;
  /** 人类可读错误消息 */
  message: string;
  /** 额外错误详情 (可选，如 ValidationError 的字段列表) */
  data?: unknown;
  /** 请求追踪 ID — 可用于后端日志关联排查 */
  trace_id: string;
}

/**
 * @deprecated 自后端重构后不再使用 RFC 7807 格式。
 * 后端现在返回 {code, message, data, trace_id}，请使用 {@link ApiErrorBody}。
 * 此处保留以避免破坏遗留引用，阶段四统一清理。
 */
export const PROBLEM_TYPE_DEFAULT = "about:blank" as const;

/**
 * @deprecated 自后端重构后不再使用 RFC 7807 格式。
 * 后端现在返回 {code, message, data, trace_id}，请使用 {@link ApiErrorBody}。
 * 此处保留以避免破坏遗留引用，阶段四统一清理。
 */
export const PROBLEM_MEDIA_TYPE = "application/problem+json" as const;

/**
 * RFC 7807 problem details object.
 *
 * Matches the Pydantic `ProblemDetail` model on the backend.
 *
 * @deprecated 自后端重构后不再使用 RFC 7807 格式。
 * 后端现在返回 {code, message, data, trace_id}，请使用 {@link ApiErrorBody}。
 * 此处保留以避免破坏遗留引用，阶段四统一清理。
 */
export interface ProblemDetail {
  /** URI reference identifying the problem type. Defaults to `about:blank`. */
  type: string;
  /** Short, human-readable summary of the problem type. */
  title: string;
  /** HTTP status code generated by the origin server. */
  status: number;
  /** Human-readable explanation specific to this occurrence. */
  detail?: string;
  /** URI reference identifying this specific occurrence. */
  instance?: string;
}

/**
 * Runtime error wrapping a {code, message, data, trace_id} response from the API.
 *
 * Throw this (or its subclasses) from fetch/Axios interceptors so call sites
 * can react to typed error bodies instead of raw HTTP statuses.
 *
 * @deprecated 旧 RFC 7807 构造函数已废弃，请使用 {@link ApiErrorBody} 格式。
 */
export class ApiError extends Error {
  /** HTTP status code from the response. */
  public readonly status: number;
  /** Backend error code (0=success, 1xxx=biz, 2xxx=system, 3xxx=infra). */
  public readonly code: number;
  /** Trace ID for correlating with backend logs (from `X-Trace-Id` header or body.trace_id). */
  public readonly traceId: string;
  /** Full parsed error body. */
  public readonly body: ApiErrorBody;
  /** Convenience accessor for `body.data`. */
  public readonly data?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.traceId = body.trace_id;
    this.body = body;
    this.data = body.data;
    // Restore prototype chain when targeting ES5 / transpiled output.
    Object.setPrototypeOf(this, ApiError.prototype);
  }

  /** Business error (1xxx range). */
  get isBizError(): boolean {
    return this.code >= 1000 && this.code < 2000;
  }

  /** System error (2xxx range and above). */
  get isSystemError(): boolean {
    return this.code >= 2000;
  }
}

/**
 * Type guard that narrows an unknown thrown value to {@link ApiError}.
 *
 * @param e - Value caught from a `try`/`catch` or rejection handler.
 * @returns `true` when `e` is an {@link ApiError} instance.
 */
export function isApiError(e: unknown): e is ApiError {
  return e instanceof ApiError;
}
